export const AppRoutes = {
  // auth routes
  login: "/auth/login",
  register: "/auth/register",
  activate: "/auth/activate",
  activateMessage: "/auth/activate-message",
  resendActivationEmail: "/auth/resend-activation-email",
  forgetPassword: "/auth/forget-password",
  forgetPasswordMessage: "/auth/forget-password-message",
  resetPassword: "/auth/reset-password",
  confirmResetPassword: "/auth/password/reset/confirm",
  resetPasswordMessage: "/auth/reset-password-message",
  // main routes
  home: "/",
  dashboard: "/dashboard",
  about: "/about",
  space: "/space",
  contact: "/contact",
  privacy: "/privacy",
  terms: "/terms",
  cookies: "/cookies",
  trustCenter: "/trust-center",
  gdpr: "/gdpr",
  abuse: "/abuse",
  notFound: "*",
};
