export const AppRoutes = {
  // auth routes
  login: "/auth/login",
  register: "/auth/register",
  activate: "/auth/activate",
  activateMessage: "/auth/activate-message",
  resendActivationEmail: "/auth/resend-activation-email",
  forgetPassword: "/auth/forget-password",
  forgetPasswordMessage: "/auth/forget-password-message",
  resetPassword: "/auth/reset-password",
  confirmResetPassword: "/auth/password/reset/confirm",
  resetPasswordMessage: "/auth/reset-password-message",
  // main routes
  home: "/",
  about: "/about",
  contact: "/contact",
  privacy: "/privacy",
  terms: "/terms",
  cookies: "/cookies",
  trustCenter: "/trust-center",
  gdpr: "/gdpr",
  abuse: "/abuse",
  pricing: "/pricing",
  notFound: "*",
  // core routes
  space: "/space",
  dashboard: "/space/dashboard",
  company: "/space/company",
  agency: "/space/agency",
  settings: "/space/settings",
};
